### ISSUE TITLE
Problem with "matb33:collection-hooks" with example?

### ISSUE THREAD

**Issue by thearabbit** [netanelgilad/meteor-excel#16]
I get error when I test this example with `matb33:collection-hooks`

``` js
W20150724-08:54:28.277(7)? (STDERR) Error: [The global definition of Mongo.Collec
tion has been patched by another package, and the prototype constructor has been 
left in an inconsistent state. Please see this link for a workaround: https://git
hub.com/vsivsi/meteor-file-sample-app/issues/2#issuecomment-120780592]           
W20150724-08:54:28.277(7)? (STDERR)     at new FileCollection (packages/vsivsi:fi
le-collection/src/gridFS_server.coffee:27:22)                                    
W20150724-08:54:28.277(7)? (STDERR)     at app\common.js:5:18                    
W20150724-08:54:28.278(7)? (STDERR)     at D:\meteor-app\Leaderboard-excel\.meteo
r\local\build\programs\server\boot.js:222:10                                     
W20150724-08:54:28.277(7)? (STDERR)     at app\common.js:25:3                    
W20150724-08:54:28.278(7)? (STDERR)     at Array.forEach (native)                
W20150724-08:54:28.278(7)? (STDERR)     at Function._.each._.forEach (C:\Users\Ra
bbit1\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_b
undle\server-lib\node_modules\underscore\underscore.js:79:11)                    
W20150724-08:54:28.278(7)? (STDERR)     at D:\meteor-app\Leaderboard-excel\.meteo
r\local\build\programs\server\boot.js:117:5                                      
```

Could you help me.

**Comment by thearabbit** [comment]
Now I found error with `matb33:collection-hooks`.
but don't know how to fix this.

**Comment by thearabbit** [comment]
Now work fine.

``` js
Mongo.Collection.prototype.constructor = Mongo.Collection;
myFiles = new FileCollection( ... );
```
