### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by garrilla** [netanelgilad/meteor-excel#2]
I expected I could use this in server code (the file is in ./public)

``` javascript
var workbook = Excel.readFile("busdem13.xls");
```

but I get an error

```
W20150106-11:48:50.593(0)? (STDERR)           
W20150106-11:48:50.596(0)? (STDERR) /home/garrilla/.meteor/packages/meteor-tool/.1.0.38.1dh3lip++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150106-11:48:50.597(0)? (STDERR)                                             throw(ex);
W20150106-11:48:50.598(0)? (STDERR)                                                   ^
W20150106-11:48:50.599(0)? (STDERR) TypeError: Object function (fileType) {                                                   // 46
W20150106-11:48:50.599(0)? (STDERR)   if (fileType != 'xlsx' && fileType != 'xls') {                                // 47
W20150106-11:48:50.600(0)? (STDERR)     throw new Meteor.Error(400, "File must be of type xlsx or xls");            // 48
W20150106-11:48:50.600(0)? (STDERR)   }                                                                             // 49
W20150106-11:48:50.600(0)? (STDERR)                                                                                 // 50
W20150106-11:48:50.601(0)? (STDERR)   this.fileType = fileType;                                                     // 51
W20150106-11:48:50.601(0)? (STDERR)   this.utils = new ExcelUtils(this.fileType);                                   // 52
W20150106-11:48:50.602(0)? (STDERR) } has no method 'readFile'
W20150106-11:48:50.602(0)? (STDERR)     at app/hello.js:25:24
W20150106-11:48:50.603(0)? (STDERR)     at app/hello.js:28:3
W20150106-11:48:50.606(0)? (STDERR)     at /home/garrilla/projects/zndbx/excelparser/.meteor/local/build/programs/server/boot.js:175:10
W20150106-11:48:50.607(0)? (STDERR)     at Array.forEach (native)
W20150106-11:48:50.608(0)? (STDERR)     at Function._.each._.forEach (/home/garrilla/.meteor/packages/meteor-tool/.1.0.38.1dh3lip++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150106-11:48:50.608(0)? (STDERR)     at /home/garrilla/projects/zndbx/excelparser/.meteor/local/build/programs/server/boot.js:86:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

```

could you give me an example of use ?

**Comment by netanelgilad** [comment]
You need to create an Excel object and then call readFile on that. 
For example in your case:
var excel = new Excel('xls');
var workbook = excel.readFile('busdem13.xls');

**Comment by garrilla** [comment]
thankyou.
