### ISSUE TITLE
Problem with new version 0.2.5?

### ISSUE THREAD

**Issue by thearabbit** [netanelgilad/meteor-excel#24]
I tried update/add new version 0.2.5

``` js
 C:\Users\Theara\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.
windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:278         
                                                throw(ex);              
                                                      ^                 
Error: ENOENT, open 'C:\Users\Theara\AppData\Local\Temp\mt-1rfrzat\os\ne
tanelgilad:excel.js'                                                    
    at Object.Future.wait (C:\Users\Theara\AppData\Local\.meteor\package
s\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fi
bers\future.js:398:15)                                                  
    at C:\tools\fs\files.js:1331:28                                     
    at Object.wrapper [as open] (C:\tools\fs\files.js:1334:20)          
    at Object.files.readBufferWithLengthAndOffset (C:\tools\fs\files.js:
1474:20)                                                                
    at C:\tools\isobuild\isopack.js:984:26                              
    at Array.forEach (native)                                           
    at Function._.each._.forEach (C:\Users\Theara\AppData\Local\.meteor\
packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_mod
ules\underscore\underscore.js:79:11)                                    
    at C:\tools\isobuild\isopack.js:982:9                               
    at Array.forEach (native)                                           
    at Function._.each._.forEach (C:\Users\Theara\AppData\Local\.meteor\
packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_mod
ules\underscore\underscore.js:79:11)                                    
    at [object Object]._.extend._loadUnibuildsFromPath (C:\tools\isobuil
d\isopack.js:942:7)                                                     
    at C:\tools\packaging\tropohouse.js:500:19                          
    at Array.forEach (native)                                           
    at Function._.each._.forEach (C:\Users\Theara\AppData\Local\.meteor\
packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_mod
ules\underscore\underscore.js:79:11)                                    
    at C:\tools\packaging\tropohouse.js:499:11                          
    at C:\tools\utils\buildmessage.js:356:18                            
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.
js:114:14)                                                              
    at C:\tools\utils\buildmessage.js:349:34                            
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.
js:114:14)                                                              
    at C:\tools\utils\buildmessage.js:347:23                            
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.
js:114:14)                                                              
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)          
    at Object.download (C:\tools\packaging\tropohouse.js:437:20)        
    at C:\tools\packaging\tropohouse.js:575:22                          
    at C:\tools\utils\buildmessage.js:356:18                            
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.
js:114:14)                                                              
    at C:\tools\utils\buildmessage.js:349:34                            
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.
```

**Comment by cskaandorp** [comment]
Hi, a friend of mine had the same issue on his windows machine. Mac doesn't have this problem. To keep going we did the following: download and unzip the zip-file of the package, and then (!) remove the semi-colons in the filenames netanelgilad:excel-tests.js, netanelgilad:excel.js (and update the package.js accordingly). Is this enough info to continue for now? I guess netanelgilad will fix it soon.

Please @netanelgilad change the filenames for our Windows-brothers ;)

**Comment by netanelgilad** [comment]
Sure thing guys. I'll do it today.

**Comment by netanelgilad** [comment]
Check out https://github.com/netanelgilad/meteor-excel/releases/tag/0.2.6. :)
